### ISSUE TITLE
一键配网和热点配网

### ISSUE THREAD

**Issue by whwxxstsyd** [espressif/esp-ali-smartliving#21]
测试一键配网时，发现配网的速度非常慢，特别是切换区域的时候，阅读了源码，发现一键配网每次都会去找全球服务器
.................................

   PK : a1gkK9zsY5h

   DN : COrd0upvij020I0A9VMx

   DS : f1c988cefd

  PID : espressif

  MID : wroom

  URL : https://iot-auth-global.aliyuncs.com/auth/bootstrap

   SM : TLS + Guider

   TS : 2524608000000

.................................

和官方的Alios比对了一下，esp-ali-smartliving 中的热点配网和一键配网个别地方存在差异

在zconfig_vendor_common.c中，该函数下

void zconfig_got_ssid_passwd_callback(uint8_t *ssid, uint8_t *passwd,
                                      uint8_t *bssid, uint8_t *token, 
                                      uint8_t auth, uint8_t encry, uint8_t channel, uint8_t token_type)

多了这么一段代码，每次执行一键配网时，都会删除flash中存储的，这里是原来Alios中没有的，而且配网速度很慢：

    //TODO:Please change it when smartconfig can got regionid
    iotx_guider_set_dynamic_region(IOTX_CLOUD_REGION_INVALID);

在awss_dev_ap.c中，该函数下 

int wifimgr_process_dev_ap_switchap_request(void *ctx, void *resource, void *remote, void *request)

多了这么一段代码，根据APP中传来的regionContent字段来直连区域，连接速度很快：

        // get region information
        str_len = 0;
        str = json_get_value_by_name(buf, len, "regionType", &str_len, 0);
        if (str) {
            // str format is like 0","xxx":"xxx", strtol only parse the integer
            uint8_t region_type = strtol(str, NULL, 10);
            //awss_debug("regionType, %d", region_type);
            if (region_type == REGION_TYPE_ID) {
                str_len = 0;
                str = json_get_value_by_name(buf, len, "regionContent", &str_len, 0);
                if (str) {
                    int region_id = strtol(str, NULL, 10);
                    //awss_debug("regionID, %d", region_id);
                    iotx_guider_set_dynamic_region(region_id);
                }
                else
                {
                    iotx_guider_set_dynamic_region(IOTX_CLOUD_REGION_INVALID);
                }
            } else if (region_type == REGION_TYPE_MQTTURL) {
                str_len = 0;
                str = json_get_value_by_name(buf, len, "regionContent", &str_len, 0);
                if (str) {
                    memset(region_url, 0, GUIDER_URL_LEN);
                    memcpy(region_url, str, str_len);
                    awss_debug("mqtturl, %s", region_url);
                    iotx_guider_set_dynamic_mqtt_url(region_url);
                }
            } else {
                awss_warn("REGION TYPE not supported");
            }

所以，一键配网是不是可以增减类似的区域字段，加快配网速度

**Comment by ESP-YJM** [comment]
这个不是我们能控制得，这是阿里 sdk 提供得源码，我们没有做修改。另外当前 smartliving 使用得 sdk 不是 Alios， 而是  https://code.aliyun.com/living_platform/ali-smartliving-device-sdk-c.git 1.6.0版本。
